### ISSUE TITLE
Some images appear to be broken

### ISSUE THREAD

**Issue by danillouz** [thedanzor/CSS-JS-Guide_rain_warcraft_scene#1]
Nice guide!

I noticed 2 images in your guide are blank:
![screen shot 2016-08-20 at 12 29 15](https://cloud.githubusercontent.com/assets/6201287/17830652/e4425c84-66d1-11e6-9a95-458114484905.png)

Also, maybe add a gif at the beginning to show the end result :)

**Comment by thedanzor** [comment]
Hey Daniel, 

Thanks for the feedback, i agree some form of gif preview would be nice and help. 
As for the 2 "blank" images, they are actually white transparent images on a white background (github), so they don't preview very well. 
Will update the readme to reflect this, but the images are there for people to grab at anytime. Without needing to pull/download the full repo.
